description: >
  Programming tutorials focused on helping you <b>just like make game</b>.
  The solutions presented are geared to be flexible, elegant, and efficient.
  No more premature pessimization!
email: jmegaffin@gmail.com
github_username: jmegaffin
title: Programmer Of The Boreal Valley
url: http://boreal.aggydaggy.com
